services:
  postgis:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dev
    ports:
      - 5432:5432
    volumes:
      - ./data/postgis:/var/lib/postgresql/data
